baseURL = "https://jheo.io"
languageCode = "ko-kr"
title = "jheo.io"
theme = "hugo-profile"
Paginate = 10
enableEmoji = true

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "tags"
category = "categories"

[params]
version = 3
favicon = "/images/fav.png"
description = "A high performance hugo theme for personal portfolio and blog."
disable_home = false
name = "June Heo"
profession = "Software Engineer"
youtube = "https://www.youtube.com/channel/UC6HKGT_6IsRap4cb586WSJg"
linkedin = "https://www.linkedin.com/in/june-heo"
blog = "https://papercut.blog"
instagram = "https://www.instagram.com/june.heo"
facebook = "https://facebook.com/mediaflow"
disable_about = false
descripe_l1_person = "애플리케이션, 모바일, 플랫폼, 클라우드 등 다양한 분야에서 개발자 및 아키텍트 업무를 경험하였습니다. 또한 다년간 신입사원 및 사내 개발자들을 대상으로 업무, 프로그래밍, 알고리즘, 프레임워크, 아키텍처 등에 대한 교육 및 세미나를 다수 진행하였습니다."
descripe_l2_person = "개발자들을 위한 개발에 관심을 많이 가지고 있으며, 개발자들이 편하게 개발할 수 있게 만들어주는 API, 서비스, 라이브러리, 문서, 유틸리티 등을 만들고 공유하는 것을 좋아합니다."
disable_experience = false
disable_education = false
disable_projects = false
disable_achievements = false
disable_contact = true
contact_content = "My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!"
email = "papercut@gmail.com"
socialiconfooter = false
recentposts = false
showdescription = false
tweet = false

  [[params.depts]]
  name = "신사업 인큐베이션팀"
  role = "소프트웨어 아키텍트"
  start = 2020
  end = "현재"

  [[params.depts]]
  name = "플랫폼개발팀"
  role = "소프트웨어 아키텍트"
  start = 2019
  end = 2020

  [[params.depts]]
  name = "아키텍처팀"
  role = "소프트웨어 아키텍트"
  start = 2018
  end = 2019

  [[params.depts]]
  name = "솔루션개발팀"
  role = "애플리케이션 개발"
  start = 2014
  end = 2017

  [[params.depts]]
  name = "소프트웨어 엔지니어링팀"
  role = "애플리케이션 개발"
  start = 2010
  end = 2014

  [[params.skills]]
  name = "Java"

  [[params.skills]]
  name = "Spring"

  [[params.skills]]
  name = "Kubernetes"

  [[params.skills]]
  name = "Redis"

  [[params.skills]]
  name = "AWS"

  [[params.skills]]
  name = "JavaScript"

  [[params.skills]]
  name = "ReactJS"

  [[params.skills]]
  name = "Cloud Native"

  [[params.skills]]
  name = "DevOps"

  [[params.skills]]
  name = "GraphQL"

  [[params.experience]]
  company = "Marimba"
  companyId = "marimba"
  role = "Software Architect"
  startdate = 2020.09
  enddate = "현재"

    [[params.experience.featuredpoints]]
    point = "사용기술 - ReactJS, JavaScript, NodeJS, Express, Redis, AWS, Kubernetes"

    [[params.experience.featuredpoints]]
    point = '<a href="https://marimba.team" target="_blank">실시간 협업을 위한 온라인 화이트보드 서비스</a> 개발'

    [[params.experience.featuredpoints]]
    point = "텍스트 에디터, 스마트 가이드, 투표 및 기타 편의 기능 프론트 엔드 및 백엔드 개발"

    [[params.experience.featuredpoints]]
    point = '<a href="/blog/a-tales-of-two-editor" target="_blank">텍스트 에디터 개발 후기</a>'

  [[params.experience]]
  company = "DevOps 플랫폼 포탈 개발"
  companyId = "portal"
  role = "Java Developer"
  startdate = 2020.01
  enddate = 2020.08

    [[params.experience.featuredpoints]]
    point = "사용기술 - Spring Boot, WebFlux, Java, JPA, VueJS, JavaScript, Redis"

    [[params.experience.featuredpoints]]
    point = "사내 클라우드, Jira, GitHub, Jenkins 기반 프로젝트 관리 및 모니터링을 위한 플랫폼 포탈 기획 / 개발"

    [[params.experience.featuredpoints]]
    point = "백엔드 및 프론트엔드 프로젝트 구성 및 개발자 교육"

    [[params.experience.featuredpoints]]
    point = "Markdown/Git 기반 개발문서 관리 서비스 백엔드 및 프론트엔드 개발"

  [[params.experience]]
  company = "Infrastructure Management System 개발"
  companyId = "ims"
  role = "Go Developer"
  startdate = 2019.09
  enddate = 2019.12

    [[params.experience.featuredpoints]]
    point = "사용기술 - Go, gRPC, VueJS, JavaScript, Kubernetes"

    [[params.experience.featuredpoints]]
    point = '사내 전략인재 파견 프로그램을 통한 해외 프로젝트 개발 참여 (<a href="http://samsung-cnct.github.io/" target="_blank">Cloud Native Computing Team / Seattle</a>)'

    [[params.experience.featuredpoints]]
    point = "베어 메탈 및 퍼블릭 클라우드 지향 K8S 클러스터 설치 및 관리 시스템 개발 프로젝트 참여"

    [[params.experience.featuredpoints]]
    point = '<a href="/blog/implement-multi-region-with-strange-language/" target="_blank">멀티 리전 디플로이 기능 백엔드 및 프론트엔드 개발</a> 수행'

    [[params.experience.featuredpoints]]
    point = '<a href="/blog/work-as-a-team" target="_blank">해외 개발 문화 체험 후기</a>'

    [[params.experience.featuredpoints]]
    point = '<a href="/blog/from-ruby-to-k8s" target="_blank">KubeCon + CloudNativeCon 2019 컨퍼런스 참석 후기</a>'

  [[params.experience]]
  company = "API Catalog 시스템 개발"
  companyId = "catalog"
  role = "Software Architect"
  startdate = 2018.12
  enddate = 2019.08

    [[params.experience.featuredpoints]]
    point = "사용기술 - Spring Boot, Kubernetes, Redis"

    [[params.experience.featuredpoints]]
    point = "사내 공통 API, 데이터, 이미지 제공을 위한 API 포탈 서비스 개발 및 운영"

    [[params.experience.featuredpoints]]
    point = "API 인증 키 발급 및 관리 시스템 개발 및 운영"

    [[params.experience.featuredpoints]]
    point = '<a href="/blog/develop-basic-crud-app/" target="_blank">API 인증 키 발급 시스템 개발 후기</a>'

  [[params.experience]]
  company = "플랫폼 기반 개발자 교육 과정 개발 및 강의"
  companyId = "e2e"
  role = "Software Architect"
  startdate = 2018.07
  enddate = 2019.06

    [[params.experience.featuredpoints]]
    point = "사용기술 - Spring Boot, Netflix Stack, MSA, Docker, Kubernetes"

    [[params.experience.featuredpoints]]
    point = "스프링 부트, MSA, VueJS 및 K8S, Cloud 기반 개발자 교육과정 교재 및 실습 교안 작성"

    [[params.experience.featuredpoints]]
    point = "스프링 기반 백엔드 및 MSA 강의 사내 강사 역할 수행"

    [[params.experience.featuredpoints]]
    point = '<a href="/blog/cloud-native-programming-101" target="_blank">클라우드 네이티브 프로그래밍 세미나 강연</a>'

  [[params.experience]]
  company = "클라우드 서비스 전환 및 공통 서비스 개발"
  companyId = "arch"
  role = "Software Architect"
  startdate = 2018.03
  enddate = 2018.11

    [[params.experience.featuredpoints]]
    point = "사용기술 - Docker, Kubernetes, Helm, Java, Spring Boot, Redis"

    [[params.experience.featuredpoints]]
    point = "사내 공통 서비스(인증, KMS, 스토리지, 번역, PDF 변환 등)를 컨테이너/Kubernetes 기반으로 전환하는 업무 담당"

    [[params.experience.featuredpoints]]
    point = "사용자 유입 통제 서비스, 캐시 서비스 등 개발하여 클라우드 기반으로 서비스"

  [[params.experience]]
  company = "S-Patch"
  companyId = "spatch"
  role = "Software Architect"
  startdate = 2016.11
  enddate = 2018.02

    [[params.experience.featuredpoints]]
    point = "사용기술 - AWS, Spring Boot, Redis, Android, Tizen"

    [[params.experience.featuredpoints]]
    point = '<a href="https://www.wellysis.com/" target="_blank">웨어러블 장비를 이용한 심전도 데이터 측정 및 분석 서비스</a> 개발'

    [[params.experience.featuredpoints]]
    point = "심전도 및 위치 정보 데이터 수집 서버, 분석 작업 스케줄러, 안드로이드 및 타이젠 클라이언트 개발"

    [[params.experience.featuredpoints]]
    point = "AWS 인프라 구성 및 운영 업무 담당"

    [[params.experience.featuredpoints]]
    point = '<a href="/blog/scale-out-with-redis" target="_blank">수평 확장 가능한 머신러닝 분석 시스템 개발 후기</a>'

  [[params.experience]]
  company = "EHR Mobile"
  companyId = "ehr"
  role = "Mobile Developer"
  startdate = 2014.03
  enddate = 2016.1

    [[params.experience.featuredpoints]]
    point = "사용기술 - Android, iOS, Java, Swift, Spring Framework, Redis"

    [[params.experience.featuredpoints]]
    point = "의사, 환자, 병원 스탭을 위한 다수의 스마트폰 및 태블릿 모바일 애플리케이션 개발"

    [[params.experience.featuredpoints]]
    point = "부서 내 모바일 개발자 교육, 양성, 선도개발 업무 수행"

    [[params.experience.featuredpoints]]
    point = "공통 라이브러리(파일관리, 네트워크, 암호화 통신, 내비게이션) 및 공통 UI컴포넌트 개발 업무 담당"

    [[params.experience.featuredpoints]]
    point = '<a href="https://youtu.be/gvPuQSfpj14" target="_blank">모바일 개발 프로젝트 준비과정 발표 슬라이드</a>'

    [[params.experience.featuredpoints]]
    point = '<a href="/blog/enterprise-android-dev" target="_blank">프로젝트 공통 라이브러리 개발 후기</a>'

  [[params.experience]]
  company = "CIC 3.0 Apps & Solution"
  companyId = "cic"
  role = "Android Developer"
  startdate = 2_013.09
  enddate = 2_014.02

    [[params.experience.featuredpoints]]
    point = "사용기술 - Android, Java, Spring Framework, jQuery"

    [[params.experience.featuredpoints]]
    point = "신입/경력 사원 교육용 안드로이드 태블릿 기반 강의 노트 필기 프로그램 개발"

    [[params.experience.featuredpoints]]
    point = "필기 프로그램 드로잉 엔진 및 주요 그래픽 처리 모듈 개발"

    [[params.experience.featuredpoints]]
    point = "서버 저장 및 양방향 동기화 모듈 개발"

  [[params.experience]]
  company = "비즈니스 프로세스 모델러"
  companyId = "bizmodeler"
  role = "Java Developer"
  startdate = 2013.03
  enddate = 2013.06

    [[params.experience.featuredpoints]]
    point = "사용기술 - Java, SWT, Spring Framework, Apache POI, Jasper Report"

    [[params.experience.featuredpoints]]
    point = "이클립스 플러그인 기반의 업무 설계서 작성 프로그램 개발"

    [[params.experience.featuredpoints]]
    point = "메타 시스템과 연동한 다국어 리포트 변환 기능 개발"

    [[params.experience.featuredpoints]]
    point = "비즈니스 프로세서 모델링 디자이너 개발"

  [[params.experience]]
  company = "ChatON Voice&Video Admin Portal"
  companyId = "chaton"
  role = "Instructor/Translator"
  startdate = 2013.07
  enddate = 2013.09

    [[params.experience.featuredpoints]]
    point = "사용기술 - Agile, Scrum, Java"

    [[params.experience.featuredpoints]]
    point = "메신저 서버의 관리 포탈 개발 및 운영 유지보수를 중국 지사로 이전하기 위한 사전 준비 프로젝트"

    [[params.experience.featuredpoints]]
    point = "중국 개발센터 리더들에 대한 업무 프로세스, 애자일, 개발 프레임워크 교육"

    [[params.experience.featuredpoints]]
    point = "설계 문서 영문 번역 및 관련 회의 통역"

  [[params.experience]]
  company = "배치 프레임워크 스케줄러"
  companyId = "aebs"
  role = "Java Developer"
  startdate = 2_012.03
  enddate = 2_012.1

    [[params.experience.featuredpoints]]
    point = "사용기술 - Java, Spring Framework, GWT, Agile, Scrum"

    [[params.experience.featuredpoints]]
    point = "스프링 배치 스케줄러 개발 및 관련 UI 개발 수행"

    [[params.experience.featuredpoints]]
    point = "스케줄러 UI 설계 및 이벤트 로직 설계"

    [[params.experience.featuredpoints]]
    point = "원격 개발팀 리드, 프로젝트 관리 및 애자일 프로세스 관리"

    [[params.experience.featuredpoints]]
    point = '<a href="https://youtu.be/KxvpPfez9hA" target="_blank">프로젝트 후기 및 Case Study 발표 슬라이드</a>'

  [[params.experience]]
  company = "전자정부 표준프레임워크"
  companyId = "egovframe"
  role = "Java Developer"
  startdate = 2010.05
  enddate = 2011.11

    [[params.experience.featuredpoints]]
    point = "사용기술 - Java, Spring Framework, JSP, jQuery"

    [[params.experience.featuredpoints]]
    point = "프레임워크 코어 버전 업데이트 작업 (스프링 2.5 -> 3.0 기반)"

    [[params.experience.featuredpoints]]
    point = '컴포넌트 재사용률 측정 서비스, <a href="https://www.egovframe.go.kr/wiki/doku.php?id=egovframework:compa" target="_blank">프레임워크 적용 여부 점검 서비스</a> 개발'

    [[params.experience.featuredpoints]]
    point = '프레임워크 개발 강의 및 <a href="https://open.egovframe.org/oc/products/seminarItem.do?nttId=2992&pageIndex=20" target="_blank">기술 세미나</a> 강의 진행'

  [[params.education]]
  degree = "석사"
  branch = "소프트웨어공학"
  university = "고려대학교 컴퓨터정보통신대학원"
  thesis = '<a href="http://www.riss.kr/search/detail/DetailView.do?p_mat_type=be54d9b8bc7cdb09&control_no=a27b094bbe0ea2a5ffe0bdc3ef48d419" target="_blank">컨테이너 기반 오토스케일링 기법의 성능 분석 및 개선</a>'
  startedyear = "2017"
  graduation = "2019"

  [[params.education]]
  degree = "학사"
  branch = "컴퓨터정보공학"
  university = "인하대학교 IT공과대학"
  startedyear = "2003"
  graduation = "2010"

  [[params.certification]]
  name = '<a href="https://www.cncf.io/certification/cka/">Certified Kubernetes Administrator</a>'
  organization = "Linux Foundation"
  certcode = '<a href="https://www.credly.com/badges/10ff5ce8-379b-4fca-ad9b-cf9f950aef0c" target="_blank">CKA-2000-005786-0100</a>'
  startedyear = "2020"
  endyear = "2023"

  [[params.certification]]
  name = '<a href="https://www.cncf.io/certification/ckad/">Certified Kubernetes Application Developer</a>'
  organization = "Linux Foundation"
  certcode = '<a href="https://www.credly.com/badges/fbd59951-31f5-4d98-aa72-fac530162b08/linked_in_profile" target="_blank">CKAD-2000-002748-0100</a>'
  startedyear = "2020"
  endyear = "2023"

  [[params.projects]]
  name = "두 에디터 이야기"
  img = "/images/portfolio/editor.png"
  featuredlink = "/blog/a-tales-of-two-editor/"
  description = "이미 오픈하여 운영하고 있는 서비스의 근간이 되는 텍스트 에디터 엔진을 완전히 다른 오픈소스로 교체하는 작업. 어떻게 날아가는 비행기의 엔진을 교체했을까요?"

  [[params.projects]]
  name = "루비에서 쿠버네티스 까지"
  img = "/images/portfolio/kubecon.png"
  featuredlink = "/blog/from-ruby-to-k8s/"
  description = "2019년도 샌디에고 KubeCon + CloudNativeCon 2019 참석 후기. 지속적으로 변하는 개발환경을 대하는 개발자들이 지금까지 개발환경을 어떻게 변화시키고 적응했는지, 이러한 맥락에서 쿠버네티스는 개발자들에게 어떤 의미로 다가오는 지에 대해서 이야기 합니다."

  [[params.projects]]
  name = "처음 보는 언어로 멀티 리전 서포트 기능 구현하기"
  img = "/images/portfolio/multiregion.png"
  featuredlink = "/blog/implement-multi-region-with-strange-language/"
  description = "한번도 써본 적 없는 개발 환경에서 Go와 gRPC로 시스템에 멀티 리전 기능을 추가하기"

  [[params.projects]]
  name = "레디스를 활용한 스케일 아웃 레시피"
  img = "/images/portfolio/scaleout.png"
  featuredlink = "/blog/scale-out-with-redis/"
  description = "레디스 하나만 사용할 수 있는 상황에서 수평 확장 가능한 마이크로 서비스 아키텍처 구성하기"

  [[params.projects]]
  name = "클라우드 네이티브 프로그래밍 101"
  img = "/images/portfolio/cloud.png"
  featuredlink = "/blog/cloud-native-programming-101/"
  description = "2018년 사내 기술 세미나 발표 후기. 클라우드 네이티브 프로그래밍을 시작하는 개발자들을 위한 안내서"

  [[params.projects]]
  name = "팀으로 일하는 것과 팀을 위해 일하는 것"
  img = "/images/portfolio/seattle.png"
  featuredlink = "/blog/work-as-a-team/"
  description = "같은 개발 환경에서도 다른 방식으로 일하는 한국과 미국 개발자들의 차이를 발생시키는 근원은 무엇일까?"

  [[params.projects]]
  name = "엔터프라이즈 안드로이드 애플리케이션 개발하기"
  img = "/images/portfolio/android.png"
  featuredlink = "/blog/enterprise-android-dev/"
  description = "모바일 개발 경험이 없는 개발팀과 함께 엔터프라이즈 앱을 만들기 위한 안드로이드 공통 라이브러리 제작기"

  [[params.projects]]
  name = "아주 간단한 CRUD 애플리케이션 만들기"
  img = "/images/portfolio/crud.png"
  featuredlink = "/blog/develop-basic-crud-app/"
  description = "아주 단순한 요구사항을 가진 API 인증키 발급 애플리케이션을 단순하지 않게 만드는 방법"

  [[params.projects]]
  name = "신입개발자 성장가이드 Part 1"
  youtubeLink = "https://www.youtube.com/embed/5AIYUamN1wY"
  youtubeSiteLink = "https://youtu.be/5AIYUamN1wY"
  description = "2021년 상반기 신입 개발자 멘토링 세션"

  [[params.projects]]
  name = "신입개발자 성장가이드 Part 2"
  youtubeLink = "https://www.youtube.com/embed/uicauWZeqMA"
  youtubeSiteLink = "https://youtu.be/uicauWZeqMA"
  description = "2021년 하반기 신입 개발자 멘토링 세션"

  [[params.projects]]
  name = "Backend 개발의 현황"
  youtubeLink = "https://www.youtube.com/embed/3gED2lpQTxc"
  youtubeSiteLink = "https://youtu.be/3gED2lpQTxc"
  description = "2020년 해외 신입 개발자 입문 교육"

  [[params.projects]]
  name = "GraphQL을 배워보자"
  youtubeLink = "https://www.youtube.com/embed/ZL4cv9ObuLM"
  youtubeSiteLink = "https://youtu.be/ZL4cv9ObuLM"
  description = "GraphQL의 소개 및 기초 개념"

  [[params.achievements]]
  title = "삼성SDS 신입개발자 조기전력화 최우수 신입사원 (2010)"
  description = "삼성SDS 신입개발자 사전교육, 배치고사, OJT 교육 성적 1위"

  [[params.achievements]]
  title = "삼성SDS 인턴사원 멘토링 우수 멘토 (2011)"
  description = "삼성SDS 2011년 하계 인턴사원 멘토링 우수 멘토 선정"

  [[params.achievements]]
  title = "삼성SDS 신입사원 멘토링 우수 멘토 (2012)"
  description = "삼성SDS 2011 ~ 2012 신입사원 멘토링 우수 멘토 선정"

  [[params.achievements]]
  title = "삼성SDS ICSP Tech 경진대회 Java 프로그래밍 1위 (2012)"
  description = "삼성SDS 전사 Java 프로그래밍 경진대회 1위"

  [[params.achievements]]
  title = "삼성그룹 대학생 멘토링 우수 멘토 (2013)"
  description = "삼성그룹 2013년도 대학생 대상 멘토링 우수 멘토 선정"

  [[params.achievements]]
  title = "삼성SDS IT석사 대상자 선정 (2017)"
  description = "사내 전략인재 양성 프로그램 중 소프트웨어공학 석사학위 취득 지원 프로그램 선정"

  [[params.achievements]]
  title = "고려대학교 컴퓨터정보통신대학원 졸업생 최우수상 (2019)"
  description = "컴퓨터정보통신대학원 수석 입학 및 수석 졸업 (총장상)"

  [[params.achievements]]
  title = "삼성SDS Global Exchange Program 대상자 선정 (2019)"
  description = "사내 전략인재 양성 프로그램 중 해외 지사 파견 근무 및 프로젝트 참여 대상자 선정"
